/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-chevron-left' : '&#xe000;',
			'icon-chevron-right' : '&#xe001;',
			'icon-chevron-up' : '&#xe002;',
			'icon-ok' : '&#xe003;',
			'icon-remove' : '&#xe004;',
			'icon-zoom-in' : '&#xe005;',
			'icon-zoom-out' : '&#xe006;',
			'icon-glass' : '&#xe007;',
			'icon-music' : '&#xe008;',
			'icon-search' : '&#xe009;',
			'icon-envelope' : '&#xe00a;',
			'icon-heart' : '&#xe00b;',
			'icon-star' : '&#xe00c;',
			'icon-star-empty' : '&#xe00d;',
			'icon-film' : '&#xe00e;',
			'icon-cog' : '&#xe00f;',
			'icon-trash' : '&#xe010;',
			'icon-home' : '&#xe011;',
			'icon-github' : '&#xe012;',
			'icon-bug' : '&#xe013;',
			'icon-apple' : '&#xe014;',
			'icon-windows' : '&#xe015;',
			'icon-android' : '&#xe016;',
			'icon-linux' : '&#xe017;',
			'icon-desktop' : '&#xe018;',
			'icon-laptop' : '&#xe019;',
			'icon-tablet' : '&#xe01a;',
			'icon-mobile' : '&#xe01b;',
			'icon-chevron-down' : '&#xe01c;',
			'icon-retweet' : '&#xe01d;',
			'icon-random' : '&#xe01e;',
			'icon-comment' : '&#xe01f;',
			'icon-tag' : '&#xe020;',
			'icon-tags' : '&#xe021;',
			'icon-rss-sign' : '&#xe022;',
			'icon-female' : '&#xe023;',
			'icon-male' : '&#xe024;',
			'icon-long-arrow-down' : '&#xe025;',
			'icon-long-arrow-up' : '&#xe026;',
			'icon-long-arrow-left' : '&#xe027;',
			'icon-long-arrow-right' : '&#xe028;',
			'icon-reorder' : '&#xe029;',
			'icon-list-ul' : '&#xe02a;',
			'icon-list-ol' : '&#xe02b;',
			'icon-cloud' : '&#xe02c;',
			'icon-warning-sign' : '&#xe02d;',
			'icon-eye-open' : '&#xe02e;',
			'icon-eye-close' : '&#xe02f;',
			'icon-step-backward' : '&#xe030;',
			'icon-fast-backward' : '&#xe031;',
			'icon-backward' : '&#xe032;',
			'icon-play' : '&#xe033;',
			'icon-pause' : '&#xe034;',
			'icon-stop' : '&#xe035;',
			'icon-forward' : '&#xe036;',
			'icon-fast-forward' : '&#xe037;',
			'icon-step-forward' : '&#xe038;',
			'icon-eject' : '&#xe039;',
			'icon-book' : '&#xe03a;',
			'icon-picture' : '&#xe03b;',
			'icon-pencil' : '&#xe03c;',
			'icon-map-marker' : '&#xe03d;',
			'icon-arrow-left' : '&#xe03e;',
			'icon-arrow-right' : '&#xe03f;',
			'icon-arrow-up' : '&#xe040;',
			'icon-arrow-down' : '&#xe041;',
			'icon-double-angle-left' : '&#xe042;',
			'icon-double-angle-right' : '&#xe043;',
			'icon-double-angle-up' : '&#xe044;',
			'icon-double-angle-down' : '&#xe045;',
			'icon-angle-left' : '&#xe046;',
			'icon-angle-right' : '&#xe047;',
			'icon-angle-up' : '&#xe048;',
			'icon-angle-down' : '&#xe049;',
			'icon-chevron-sign-left' : '&#xe04a;',
			'icon-chevron-sign-right' : '&#xe04b;',
			'icon-chevron-sign-up' : '&#xe04c;',
			'icon-chevron-sign-down' : '&#xe04d;',
			'icon-html5' : '&#xe04e;',
			'icon-play-sign' : '&#xe04f;',
			'icon-youtube' : '&#xe050;',
			'icon-ticket' : '&#xe051;',
			'icon-code' : '&#xe052;',
			'icon-terminal' : '&#xe053;',
			'icon-flag-alt' : '&#xe054;',
			'icon-caret-left' : '&#xe055;',
			'icon-caret-right' : '&#xe056;',
			'icon-sort' : '&#xe057;',
			'icon-sort-down' : '&#xe058;',
			'icon-sort-up' : '&#xe059;',
			'icon-envelope-alt' : '&#xe05a;',
			'icon-comment-alt' : '&#xe05b;',
			'icon-umbrella' : '&#xe05c;',
			'icon-comments-alt' : '&#xe05d;',
			'icon-cloud-download' : '&#xe05e;',
			'icon-cloud-upload' : '&#xe05f;',
			'icon-file-alt' : '&#xe060;',
			'icon-caret-up' : '&#xe061;',
			'icon-caret-down' : '&#xe062;',
			'icon-google-plus-sign' : '&#xe063;',
			'icon-google-plus' : '&#xe064;',
			'icon-globe' : '&#xe065;',
			'icon-circle-arrow-up' : '&#xe066;',
			'icon-circle-arrow-down' : '&#xe067;',
			'icon-circle-arrow-left' : '&#xe068;',
			'icon-circle-arrow-right' : '&#xe069;',
			'icon-hdd' : '&#xe06a;',
			'icon-rss' : '&#xe06b;',
			'icon-twitter' : '&#xe06c;',
			'icon-external-link' : '&#xe06d;',
			'icon-comments' : '&#xe06e;',
			'icon-cogs' : '&#xe06f;',
			'icon-camera-retro' : '&#xe070;',
			'icon-twitter-sign' : '&#xe071;',
			'icon-facebook-sign' : '&#xe072;',
			'icon-resize-small' : '&#xe073;',
			'icon-resize-full' : '&#xe074;',
			'icon-share-alt' : '&#xe075;',
			'icon-remove-circle' : '&#xe076;',
			'icon-ok-circle' : '&#xe077;',
			'icon-ban-circle' : '&#xe078;',
			'icon-share' : '&#xe079;',
			'icon-off' : '&#xe07a;',
			'icon-list-alt' : '&#xe07b;',
			'icon-vk' : '&#xe07c;',
			'icon-check-sign' : '&#xe07d;',
			'icon-windows-2' : '&#xe07e;',
			'icon-lab' : '&#xe07f;',
			'icon-html5-2' : '&#xe080;',
			'icon-chrome' : '&#xe081;',
			'icon-firefox' : '&#xe082;',
			'icon-IE' : '&#xe083;',
			'icon-opera' : '&#xe084;',
			'icon-safari' : '&#xe085;',
			'icon-heart-empty' : '&#xe086;',
			'icon-fire' : '&#xe087;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};