name: Пироги с фронтендом
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
relative_permalinks: false

exclude: ['README.md']
permalink: /:categories/:title

loc:
    name:
        ru: "Утром доделаю"
        en: "Will finish in the morning"
    in_lang:
        ru: "RU"
        eng: "EN"
    footer:
        ru: "Работает на Jekyll"
        en: "Powered by Jekyll"