name: Утром доделаю
markdown: kramdown
pygments: true
relative_permalinks: false

exclude: ['README.md']
permalink: /:categories/:title

cats:
    rare-species:
        ru: "Редкие звери"
        en: "Rare species"
        link: "rare-species"

loc:
    name:
        ru: "Утром доделаю"
        en: "Will finish in the morning"
    in_lang:
        ru: "RU"
        en: "EN"
    original_image:
        ru: "Посмотреть оригинал"
        en: "Original image"
    footer:
        ru: Кое-как работает на <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab"></i>&nbsp;<span>Jekyll</span></a>. Смотрите, это же <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github"></i>&nbsp;<span>GitHub</span></a>!
        en: Somehow it works on <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab"></i>&nbsp;<span>Jekyll</span></a>. Look, it's <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github"></i>&nbsp;<span>GitHub</span></a>!