name: Утром доделаю
markdown: kramdown
pygments: true
relative_permalinks: false

exclude: ['README.md','node_modules','temp','_src','package.json','Gruntfile.js']
permalink: /:categories/:title/

path:
    ru: "/"
    en: "/en/"

cats:
    rare-species:
        ru: "Редкие звери"
        in: "Редких зверях"
        en: "Rare species"
        link: "rare-species"
    experiments:
        ru: "Эксперименты"
        in: "Экспериментах"
        en: "Experiments"
        link: "experiments"
    scripts:
        ru: "Скрипты"
        in: "Скриптах"
        en: "Scripts"
        link: "scripts"
    internet-maintenance:
        ru: "Чиним интернет"
        in: "Чиним интернет"
        in_r: true
        en: "Internet maintenance"
        link: "internet-maintenance"

loc:
    name:
        ru: "Утром доделаю"
        en: "Will finish in the morning"
    in_lang:
        ru: "RU"
        en: "EN"
    original_image:
        ru: "Посмотреть оригинал"
        en: "Original image"
    published:
        ru: 'Опубликовано'
        en: 'Published on'
    footer:
        ru:
            - <a href="/" class="iconlink">«<span>Утром доделаю</span>»</a> работает на <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab">&nbsp;</i><span>Jekyll</span></a>
            - Сорс бложека и другие штуки на <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github">&nbsp;</i><span>ГитХабе</span></a>
            - Комментарии, баги, замечания&nbsp;&rarr; <a href="mailto:wd@dizaina.net" class="iconlink"><i class="icon-envelope">&nbsp;</i><span>wd@dizaina.net</span></a>
        en:
            - <a href="/en/" class="iconlink">“<span>Will finish in the morning</span>”</a> is powered by <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab">&nbsp;</i><span>Jekyll</span></a>
            - Blog’s source&nbsp;& other stuff on <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github">&nbsp;</i><span>GitHub</span></a>
            - Comments, bugs&nbsp;& remarks&nbsp;&rarr; <a href="mailto:wd@dizaina.net" class="iconlink"><i class="icon-envelope">&nbsp;</i><span>wd@dizaina.net</span></a>

header_scripts.js: 2f675fa2ed9a08b3545b263c0bda7ef1
scripts.js: fdc94d5197df6f8fa54d2864907b2cb6
selectivizr.min.js: ece63dfdab779d4a19395d12105514a9
steam\modernizr.js: 4a2a2435ea8e4b07cfba576dec176785
steam\scripts.js: f1914ef33edeb64d8e4c4784acbc9093
ie7.css: 6fb19fedd8f480352ba3fe5360d2572a
ie8.css: 8ed1467567b287310235e1ddf9ce1d93
steam\styles.css: 335ef0c189ec4124084f2758c29da605
style.css: cbe434ccfd4c2cadb523cd202ec9b3c5
steam\ie.css: eee577a33f2fadd1915661d2b8480b19
