name: Утром доделаю
markdown: kramdown
pygments: true
relative_permalinks: false

exclude: ['README.md']
permalink: /:categories/:title/

path:
    ru: "/"
    en: "/en/"

cats:
    rare-species:
        ru: "Редкие звери"
        in: "Редких зверях"
        en: "Rare species"
        link: "rare-species"
    experiments:
        ru: "Эксперименты"
        in: "Экспериментах"
        en: "Experiments"
        link: "experiments"
    scripts:
        ru: "Скрипты"
        in: "Скриптах"
        en: "Scripts"
        link: "scripts"
    internet-maintenance:
        ru: "Чиним интернет"
        in: "Чиним интернет"
        in_r: true
        en: "Internet maintenance"
        link: "internet-maintenance"

loc:
    name:
        ru: "Утром доделаю"
        en: "Will finish in the morning"
    in_lang:
        ru: "RU"
        en: "EN"
    original_image:
        ru: "Посмотреть оригинал"
        en: "Original image"
    published:
        ru: 'Опубликовано'
        en: 'Published on'
    footer:
        ru:
            - <a href="/" class="iconlink">«<span>Утром доделаю</span>»</a> работает на <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab">&nbsp;</i><span>Jekyll</span></a>
            - Сорс бложека и другие штуки на <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github">&nbsp;</i><span>ГитХабе</span></a>
            - Комментарии, баги, замечания&nbsp;&rarr; <a href="mailto:wd@dizaina.net" class="iconlink"><i class="icon-envelope">&nbsp;</i><span>wd@dizaina.net</span></a>
        en:
            - <a href="/en/" class="iconlink">“<span>Will finish in the morning</span>”</a> is powered by <a href="//jekyllrb.com" class="iconlink"><i class="icon-lab">&nbsp;</i><span>Jekyll</span></a>
            - Blog’s source&nbsp;& other stuff on <a href="//github.com/wilddeer" class="iconlink"><i class="icon-github">&nbsp;</i><span>GitHub</span></a>
            - Comments, bugs&nbsp;& remarks&nbsp;&rarr; <a href="mailto:wd@dizaina.net" class="iconlink"><i class="icon-envelope">&nbsp;</i><span>wd@dizaina.net</span></a>